version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sveltekit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sveltekit_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge